---
- name: debian | Installing Pre-Reqs
  ansible.builtin.apt:
    name: "{{ kea_dhcp_pre_reqs }}"
    state: present
  become: true
  register: result
  until: result is successful

- name: debian | Ensuring /etc/apt/keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: debian | Adding Kea DHCP Repo Key
  ansible.builtin.get_url:
    url: "{{ kea_dhcp_repo_key }}"
    dest: /etc/apt/keyrings/isc-kea.asc
    owner: root
    group: root
    mode: "0644"
  become: true

- name: debian | Adding Kea DHCP Repo
  ansible.builtin.apt_repository:
    repo: "{{ kea_dhcp_repo }}"
    state: present
  become: true

- name: debian | Installing Kea DHCP Packages
  ansible.builtin.apt:
    name: "{{ kea_dhcp_packages }}"
    state: present
  become: true
  register: result
  until: result is successful
